import lume from "lume/mod.ts";
import jsx_preact from "lume/plugins/jsx_preact.ts";
import attributes from "lume/plugins/attributes.ts";
import base_path from "lume/plugins/base_path.ts";
import code_highlight from "lume/plugins/code_highlight.ts";
import date from "lume/plugins/date.ts";
import esbuild from "lume/plugins/esbuild.ts";
import eta from "lume/plugins/eta.ts";
import feed from "lume/plugins/feed.ts";
import filter_pages from "lume/plugins/filter_pages.ts";
import inline from "lume/plugins/inline.ts";
import katex from "lume/plugins/katex.ts";
import liquid from "lume/plugins/liquid.ts";
import mdx from "lume/plugins/mdx.ts";
import metas from "lume/plugins/metas.ts";
import minify_html from "lume/plugins/minify_html.ts";
import modify_urls from "lume/plugins/modify_urls.ts";
import multilanguage from "lume/plugins/multilanguage.ts";
import nav from "lume/plugins/nav.ts";
import on_demand from "lume/plugins/on_demand.ts";
import pagefind from "lume/plugins/pagefind.ts";
import picture from "lume/plugins/picture.ts";
import imagick from "lume/plugins/imagick.ts";
import pug from "lume/plugins/pug.ts";
import relations from "lume/plugins/relations.ts";
import relative_urls from "lume/plugins/relative_urls.ts";
import remark from "lume/plugins/remark.ts";
import resolve_urls from "lume/plugins/resolve_urls.ts";
import sheets from "lume/plugins/sheets.ts";
import sitemap from "lume/plugins/sitemap.ts";
import slugify_urls from "lume/plugins/slugify_urls.ts";
import source_maps from "lume/plugins/source_maps.ts";
import svgo from "lume/plugins/svgo.ts";
import tailwindcss from "lume/plugins/tailwindcss.ts";
import postcss from "lume/plugins/postcss.ts";
import terser from "lume/plugins/terser.ts";
import toml from "lume/plugins/toml.ts";
import vento from "lume/plugins/vento.ts";

const site = lume();

site.use(jsx_preact());
site.use(attributes());
site.use(base_path());
site.use(code_highlight());
site.use(date());
site.use(esbuild());
site.use(eta());
site.use(feed());
site.use(filter_pages());
site.use(inline());
site.use(katex());
site.use(liquid());
site.use(mdx());
site.use(metas());
site.use(minify_html());
site.use(modify_urls());
site.use(multilanguage());
site.use(nav());
site.use(on_demand());
site.use(pagefind());
site.use(picture());
site.use(picture());
site.use(imagick());
site.use(pug());
site.use(relations());
site.use(relative_urls());
site.use(remark());
site.use(resolve_urls());
site.use(sheets());
site.use(sitemap());
site.use(slugify_urls());
site.use(source_maps());
site.use(svgo());
site.use(tailwindcss());
site.use(postcss());
site.use(terser());
site.use(toml());
site.use(vento());

export default site;
